<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Juego de Apuestas</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php Tag::css('kumbia') ?>
        <?= Html::includeCss() ?>
        <link href="css/bootstrap.min.css" rel="stylesheet" />
        <link href="css/font-awesome.css" rel="stylesheet" />
        <script src="js/jquery-2.1.1.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.validate.js"></script>
    </head>
    <body>
    <body>
        <nav class="navbar navbar-default">
            <center>
                <h3>Juego de Apuestas</h3>
            </center>
        </nav>
        <?php View::content() ?>
    </body>
</html>
